title: Mentorship as a Catalyst
description: Exploring Support Systems in Master of Social Work Graduate Training
theme: jekyll-theme-cayman

url: "https://mmonfils.github.io"
baseurl: "/msw-mentorship-critical-pedagogy-workshop"

source: .
destination: _site
incremental: false

sass:
  style: compressed
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - README.md